fix #2

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -2,19 +2,19 @@ name: 01 - Building Blocks
 on: [push, workflow_dispatch]
 
 jobs:
- name: echo-hello
- runs-on: ubuntu-latest
-  steps:
-  - name: Say hello
-    run: echo "Hello,World!"
- name: echo-goodbye
- runs-on: ubuntu-latest
-  steps:
-  - name: Failed step
-    run: |
-     echo "I"
-     echo "will"
-     echo "fail"
-     exit 404
-  - name: Say goodbye
-    run: printf "Goodbye!"
+   echo-hello:
+   runs-on: ubuntu-latest
+   steps:
+    - name: Say hello
+      run: echo "Hello,World!"
+   echo-goodbye:
+   runs-on: ubuntu-latest
+   steps:
+    - name: Failed step
+      run: |
+       echo "I"
+       echo "will"
+       echo "fail"
+       exit 404
+    - name: Say goodbye
+      run: printf "Goodbye!"
